version: "3.8"
services:
    nodeserver:
        build:
            context: .
        ports:
            - "4000"
    nginx:
        image: nginx
        restart: always
        ports:
            - "8080:80"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
            - ./packages/frontend/build:/var/www/html:ro